### ISSUE TITLE
Azure credentials throws TaskCanceledException when Actor is already stopped

### ISSUE THREAD

**Issue by Privarozenbeek** [petabridge/Akka.Persistence.Azure#248]
We see the following exception occurring during deployment or our Akka.net:
![image](https://user-images.githubusercontent.com/102965865/191703567-59a9293c-8eb9-43bc-9235-19341207e4d9.png)

It is expected that running tasks getting nicely cancelled by an (already) stopped actor, but we sometimes get couple of them and on any release so our alerts and monitors are gonna give false exception alerts now. 

Any suggestions?

**Comment by Aaronontheweb** [comment]
@Arkatufus is this an error from inside Azure's SDK or our own code?

**Comment by Arkatufus** [comment]
I'll look into it

**Comment by Arkatufus** [comment]
We definetly need to implement a better async housekeeping in the module, I'm just not sure it would fix the the original issue.

**Comment by Arkatufus** [comment]
I've made a PR ( #249) that might be able to address this.
This might or might not resolve the issue, depending if the underlying driver themselves throws on token cancellation, if that is the case, we would also need to wrap everything with a try...catch block

**Comment by Aaronontheweb** [comment]
Believe this is fixed via #249

**Comment by Privarozenbeek** [comment]
@Aaronontheweb will update it after the weekend, will see if we still get this.

**Comment by Aaronontheweb** [comment]
@Privarozenbeek I'm not sure if we're going to push a new update to NuGet until after https://github.com/petabridge/Akka.Persistence.Azure/issues/251 is resolved.

**Comment by Privarozenbeek** [comment]
We have dependabot running so we will m,onitor it over time.
